server:
  port: 8083
  tomcat:
    max-http-form-post-size: 314572800
spring:
  application:
    name: df_index_a
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  #  文件上传大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  profiles:
    active: pro
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml


